### ISSUE TITLE
request clarification on the specifications on StopCell

### ISSUE THREAD

**Issue by henveloper** [CastleLab/COMP3021-2021Fall-PA1-Student-Version#3]
COMP3021-2021Fall-PA1-Student-Version/app/src/main/java/hk/ust/cse/comp3021/pa1/model/StopCell.java

What do I return for `StopCell.setEntity(args)` ? The previous entity of the cell?

Skeleton:
```
/**
     * Same as {@link EntityCell#setEntity(Entity)}, with additional checking.
     *
     * @throws IllegalArgumentException if the entity is not {@code null} and not an instance of {@link Player}.
     */
    @Nullable
    @Override
    public Entity setEntity(@Nullable final Entity newEntity) {
        // TODO
//        return null;
    }
```

**Comment by henryhchchc** [comment]
I think the documentation has already told you what to do. 
> ``` java
> Same as {@link EntityCell#setEntity(Entity)}, with additional checking.
> ```
